# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.9 on 2017-02-13 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 1.9.9 on 2017-02-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models
>>>>>>> e40b9e8788a8e771bf01112953d17bc201882407


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> e40b9e8788a8e771bf01112953d17bc201882407
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
<<<<<<< HEAD
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> e40b9e8788a8e771bf01112953d17bc201882407
            ],
        ),
    ]
